# Copyright 2026
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit git-r3 toolchain-funcs

DESCRIPTION="PDFium - PDF rendering and manipulation library (upstream, GN/Ninja)"
HOMEPAGE="https://pdfium.googlesource.com/pdfium/"

EGIT_REPO_URI="https://pdfium.googlesource.com/pdfium.git"

LICENSE="Apache-2.0 BSD IJG LGPL-2.1+ MIT ZLIB"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="debug skia fontations xfa v8 test"
RESTRICT="!test? ( test ) network-sandbox"

# NOTE:
# - depot_tools provides gclient and other chromium tooling.
# - svn is still used by some DEPS flows; keep it.
BDEPEND="
	dev-util/depot-tools
	dev-util/gn
	dev-util/ninja
	>=dev-lang/python-3.10
	dev-vcs/git
	dev-vcs/subversion
"
# These may or may not be used depending on bundled third_party, but are safe as baseline.
DEPEND="
	sys-libs/zlib
	media-libs/freetype
	media-libs/fontconfig
	media-libs/libpng
	virtual/jpeg
"
RDEPEND="${DEPEND}"

# git-r3 clones into ${WORKDIR}/${P}
S="${WORKDIR}/${P}"

pkg_pretend() {
	ewarn "This live ebuild runs 'gclient sync' to fetch DEPS (network required)."
	ewarn "RESTRICT=network-sandbox is set accordingly."
}

_pdfium_export_depot_tools_path() {
	# Gentoo depot-tools often doesn't install gclient into /usr/bin
	export PATH="${EPREFIX}/usr/lib/depot_tools:${EPREFIX}/usr/share/depot_tools:${PATH}"
	export DEPOT_TOOLS_UPDATE=0
}

_pdfium_gn_args() {
	local args=(
		"use_remoteexec=false"
		"pdf_is_standalone=true"
		"is_component_build=false"
		"clang_use_chrome_plugins=false"
		"use_sysroot=false"
	)

	use debug && args+=( "is_debug=true" ) || args+=( "is_debug=false" )
	use skia && args+=( "pdf_use_skia=true" ) || args+=( "pdf_use_skia=false" )
	use fontations && args+=( "pdf_enable_fontations=true" ) || args+=( "pdf_enable_fontations=false" )

	# XFA implies V8 upstream; allow explicit v8 too.
	if use xfa; then
		args+=( "pdf_enable_xfa=true" "pdf_enable_v8=true" )
	else
		args+=( "pdf_enable_xfa=false" )
		use v8 && args+=( "pdf_enable_v8=true" ) || args+=( "pdf_enable_v8=false" )
	fi

	printf '%s\n' "${args[@]}"
}

src_unpack() {
	git-r3_src_unpack

	_pdfium_export_depot_tools_path
	command -v gclient >/dev/null || die "gclient not found (install dev-util/depot-tools or fix PATH)"

	# gclient wants a .gclient "root" directory.
	# We'll make the gclient root = ${WORKDIR} and solution name = ${P}.
	cd "${WORKDIR}" || die

	cat > .gclient <<-EOF || die
solutions = [
  {
    "name": "${P}",
    "url": "https://pdfium.googlesource.com/pdfium.git",
    "deps_file": "DEPS",
    "managed": False,
  },
]
EOF

	# Sync DEPS (downloads lots of stuff). --no-history reduces size.
	# Use -v to ease debugging in build.log.
	gclient sync --no-history -v || die "gclient sync failed"
}

src_configure() {
	local outdir="out/Release"
	use debug && outdir="out/Debug"

	mkdir -p "${outdir}" || die

	{
		echo "# Generated by Gentoo ebuild"
		_pdfium_gn_args
	} > "${outdir}/args.gn" || die

	gn gen "${outdir}" || die
}

src_compile() {
	local outdir="out/Release"
	use debug && outdir="out/Debug"

	# Reasonable default targets; pdfium_all exists in many revisions but may change.
	# We'll try pdfium_all first, fallback to pdfium_test (common).
	if ninja -C "${outdir}" -n pdfium_all >/dev/null 2>&1; then
		ninja -C "${outdir}" pdfium_all || die
	else
		ninja -C "${outdir}" pdfium_test || die
	fi
}

src_test() {
	local outdir="out/Release"
	use debug && outdir="out/Debug"

	# Build and run what exists (targets can change across snapshots).
	local targets=()
	ninja -C "${outdir}" -n pdfium_unittests >/dev/null 2>&1 && targets+=( pdfium_unittests )
	ninja -C "${outdir}" -n pdfium_embeddertests >/dev/null 2>&1 && targets+=( pdfium_embeddertests )

	[[ ${#targets[@]} -gt 0 ]] || die "No known test targets found in this snapshot"

	ninja -C "${outdir}" "${targets[@]}" || die

	[[ -x "${outdir}/pdfium_unittests" ]] && "${outdir}/pdfium_unittests" || die
	[[ -x "${outdir}/pdfium_embeddertests" ]] && "${outdir}/pdfium_embeddertests" || die
}

src_install() {
	local outdir="out/Release"
	use debug && outdir="out/Debug"

	# Public headers
	insinto /usr/include/pdfium
	doins -r public/* || die

	# Best-effort library install (layout varies)
	local so a lib_found=0

	so=$(find "${outdir}" -maxdepth 8 -type f -name 'libpdfium.so*' | head -n1)
	if [[ -n "${so}" ]]; then
		dolib.so "${so}" || die
		lib_found=1
	fi

	a=$(find "${outdir}" -maxdepth 10 -type f -name 'libpdfium.a' | head -n1)
	if [[ -n "${a}" ]]; then
		dolib.a "${a}" || die
		lib_found=1
	fi

	[[ ${lib_found} -eq 1 ]] || die "Could not find libpdfium.{so,a} under ${outdir}; layout changed."

	# Optional tool (often present)
	[[ -x "${outdir}/pdfium_test" ]] && dobin "${outdir}/pdfium_test"

	dodoc README.md || die
}
