# Copyright 1999-2018 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=8

NPM_MODULE="estree-walker"
inherit npm

DESCRIPTION="Simple utility for walking an ESTree-compliant AST, such as one generated by acorn."
HOMEPAGE="https://github.com/Rich-Harris/estree-walker"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"

RDEPEND="
        dev-nodejs/types-estree
"



